name: 'Jira issue query'
description: 'Queries a given jira issue id'
outputs:
  issue-keys:
    description: 'A comma delimited list of issue keys'
runs:
  using: 'node16'
  main: '../lib/find-pr-issue.js'
